var error=document.getElementById("error");function ajaxRequest(){var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"];if(window.ActiveXObject)for(var b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}else return window.XMLHttpRequest?new XMLHttpRequest:!1}
function saveScore(){var a=new ajaxRequest;a.onreadystatechange=function(){4==a.readyState&&(200==a.status||-1==window.location.href.indexOf("http")?(document.getElementById("menu").innerHTML=a.responseText,"Score successfully saved!"!=a.responseText&&(document.getElementById("save").style.display="block"),getScores()):error.innerHTML="An error has occured making the request")};var b=encodeURIComponent(document.getElementById("name").value);2>document.getElementById("name").value.length&&(error.innerHTML=
"You must include a name longer than 2 characters.");4;b="name="+b+"&score="+g.score+"&game=velocity";a.open("POST","http://www.stewtopia.co.uk/AJAXPHP/SaveHighscore.php",!0);a.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.send(b)}
function getScores(){var a=new ajaxRequest;a.onreadystatechange=function(){4==a.readyState&&(200==a.status||-1==window.location.href.indexOf("http")?document.getElementById("highscores").innerHTML=a.responseText:error.innerHTML="An error has occured making the request")};a.open("GET","http://www.stewtopia.co.uk/AJAXPHP/GetHighscores.php",!0);a.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.send()}
WebGLUtils=function(){var a=function(a,c){for(var d=["webgl","experimental-webgl","webkit-3d","moz-webgl"],e=null,h=0;h<d.length;++h){try{e=a.getContext(d[h],c)}catch(k){}if(e)break}return e};return{create3DContext:a,setupWebGL:function(b,c){function d(a){var c=b.parentNode;c&&(c.innerHTML='<table style="background-color: #8CE; width: 100%; height: 100%;"><tr><td align="center"><div style="display: table-cell; vertical-align: middle;"><div style="">'+a+"</div></div></td></tr></table>")}if(!window.WebGLRenderingContext)return d('This page requires a browser that supports WebGL.<br/><a href="http://get.webgl.org">Click here to upgrade your browser.</a>'),
null;var e=a(b,c);e||d('It doesn\'t appear your computer can support WebGL.<br/><a href="http://get.webgl.org/troubleshooting/">Click here for more information.</a>');return e}}}();window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a,b){return window.setTimeout(a,1E3/60)}}();
window.cancelAnimFrame=function(){return window.cancelAnimationFrame||window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||window.msCancelAnimationFrame||window.clearTimeout}();
WebGLDebugUtils=function(){function a(a){if(null==m){m={};for(var b in a)"number"==typeof a[b]&&(m[a[b]]=b)}}function b(){if(null==m)throw"WebGLDebugUtils.init(ctx) not called";}function c(a){b();var c=m[a];return void 0!==c?"gl."+c:"/*UNKNOWN WebGL ENUM*/ 0x"+a.toString(16)+""}function d(a,b,d,e){a=f[a];return void 0!==a&&(a=a[b],void 0!==a&&a[d])?c(e):null===e?"null":void 0===e?"undefined":e.toString()}function e(a,b,c){a.__defineGetter__(c,function(){return b[c]});a.__defineSetter__(c,function(a){b[c]=
a})}function h(b,f,k,n){function m(a,b){return function(){k&&k(b,arguments);var c=a[b].apply(a,arguments),l=n.getError();0!=l&&(u[l]=!0,f(l,b,arguments));return c}}n=n||b;a(b);f=f||function(a,b,l){for(var e="",h=l.length,f=0;f<h;++f)e+=(0==f?"":", ")+d(b,h,f,l[f]);a="WebGL error "+c(a)+" in "+b+"("+e+")";window.console&&window.console.error?window.console.error(a):window.console&&window.console.log&&window.console.log(a)};var u={},v={},s;for(s in b)if("function"==typeof b[s])if("getExtension"!=s)v[s]=
m(b,s);else{var t=m(b,s);v[s]=function(){var a=t.apply(b,arguments);return h(a,f,k,n)}}else e(v,b,s);v.getError=function(){for(var a in u)if(u.hasOwnProperty(a)&&u[a])return u[a]=!1,a;return b.NO_ERROR};return v}function k(a){var b=a.getParameter(a.MAX_VERTEX_ATTRIBS),c=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c);for(var d=0;d<b;++d)a.disableVertexAttribArray(d),a.vertexAttribPointer(d,4,a.FLOAT,!1,0,0),a.vertexAttrib1f(d,0);a.deleteBuffer(c);b=a.getParameter(a.MAX_TEXTURE_IMAGE_UNITS);for(d=
0;d<b;++d)a.activeTexture(a.TEXTURE0+d),a.bindTexture(a.TEXTURE_CUBE_MAP,null),a.bindTexture(a.TEXTURE_2D,null);a.activeTexture(a.TEXTURE0);a.useProgram(null);a.bindBuffer(a.ARRAY_BUFFER,null);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,null);a.bindFramebuffer(a.FRAMEBUFFER,null);a.bindRenderbuffer(a.RENDERBUFFER,null);a.disable(a.BLEND);a.disable(a.CULL_FACE);a.disable(a.DEPTH_TEST);a.disable(a.DITHER);a.disable(a.SCISSOR_TEST);a.blendColor(0,0,0,0);a.blendEquation(a.FUNC_ADD);a.blendFunc(a.ONE,a.ZERO);
a.clearColor(0,0,0,0);a.clearDepth(1);a.clearStencil(-1);a.colorMask(!0,!0,!0,!0);a.cullFace(a.BACK);a.depthFunc(a.LESS);a.depthMask(!0);a.depthRange(0,1);a.frontFace(a.CCW);a.hint(a.GENERATE_MIPMAP_HINT,a.DONT_CARE);a.lineWidth(1);a.pixelStorei(a.PACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);a.UNPACK_COLORSPACE_CONVERSION_WEBGL&&a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,a.BROWSER_DEFAULT_WEBGL);
a.polygonOffset(0,0);a.sampleCoverage(1,!1);a.scissor(0,0,a.canvas.width,a.canvas.height);a.stencilFunc(a.ALWAYS,0,4294967295);a.stencilMask(4294967295);a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.viewport(0,0,a.canvas.width,a.canvas.height);for(a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT|a.STENCIL_BUFFER_BIT);a.getError(););}var f={enable:{1:{0:!0}},disable:{1:{0:!0}},getParameter:{1:{0:!0}},drawArrays:{3:{0:!0}},drawElements:{4:{0:!0,2:!0}},createShader:{1:{0:!0}},getShaderParameter:{2:{1:!0}},getProgramParameter:{2:{1:!0}},
getShaderPrecisionFormat:{2:{0:!0,1:!0}},getVertexAttrib:{2:{1:!0}},vertexAttribPointer:{6:{2:!0}},bindTexture:{2:{0:!0}},activeTexture:{1:{0:!0}},getTexParameter:{2:{0:!0,1:!0}},texParameterf:{3:{0:!0,1:!0}},texParameteri:{3:{0:!0,1:!0,2:!0}},texImage2D:{9:{0:!0,2:!0,6:!0,7:!0},6:{0:!0,2:!0,3:!0,4:!0}},texSubImage2D:{9:{0:!0,6:!0,7:!0},7:{0:!0,4:!0,5:!0}},copyTexImage2D:{8:{0:!0,2:!0}},copyTexSubImage2D:{8:{0:!0}},generateMipmap:{1:{0:!0}},compressedTexImage2D:{7:{0:!0,2:!0}},compressedTexSubImage2D:{8:{0:!0,
6:!0}},bindBuffer:{2:{0:!0}},bufferData:{3:{0:!0,2:!0}},bufferSubData:{3:{0:!0}},getBufferParameter:{2:{0:!0,1:!0}},pixelStorei:{2:{0:!0,1:!0}},readPixels:{7:{4:!0,5:!0}},bindRenderbuffer:{2:{0:!0}},bindFramebuffer:{2:{0:!0}},checkFramebufferStatus:{1:{0:!0}},framebufferRenderbuffer:{4:{0:!0,1:!0,2:!0}},framebufferTexture2D:{5:{0:!0,1:!0,2:!0}},getFramebufferAttachmentParameter:{3:{0:!0,1:!0,2:!0}},getRenderbufferParameter:{2:{0:!0,1:!0}},renderbufferStorage:{4:{0:!0,1:!0}},clear:{1:{0:!0}},depthFunc:{1:{0:!0}},
blendFunc:{2:{0:!0,1:!0}},blendFuncSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},blendEquation:{1:{0:!0}},blendEquationSeparate:{2:{0:!0,1:!0}},stencilFunc:{3:{0:!0}},stencilFuncSeparate:{4:{0:!0,1:!0}},stencilMaskSeparate:{2:{0:!0}},stencilOp:{3:{0:!0,1:!0,2:!0}},stencilOpSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},cullFace:{1:{0:!0}},frontFace:{1:{0:!0}},drawArraysInstancedANGLE:{4:{0:!0}},drawElementsInstancedANGLE:{5:{0:!0,2:!0}},blendEquationEXT:{1:{0:!0}}},m=null;return{init:a,mightBeEnum:function(a){b();return void 0!==
m[a]},glEnumToString:c,glFunctionArgToString:d,glFunctionArgsToString:function(a,b){for(var c="",e=b.length,h=0;h<e;++h)c+=(0==h?"":", ")+d(a,e,h,b[h]);return c},makeDebugContext:h,makeLostContextSimulatingCanvas:function(a){function b(a){return"function"==typeof a?a:function(b){a.handleEvent(b)}}function c(){for(var a=Object.keys(y),b=0;b<a.length;++b)delete y[a]}function d(){++z;w||C==z&&a.loseContext()}function h(a,b){var c=a[b];return function(){d();if(!w)return c.apply(a,arguments)}}function f(a){return{statusMessage:a,
preventDefault:function(){D=!0}}}function m(a){for(var b in a)"function"==typeof a[b]?t[b]=h(a,b):e(t,a,b);t.getError=function(){d();if(!w)for(var a;a=s.getError();)y[a]=!0;for(a in y)if(y[a])return delete y[a],a;return t.NO_ERROR};var c="createBuffer createFramebuffer createProgram createRenderbuffer createShader createTexture".split(" ");for(b=0;b<c.length;++b){var f=c[b];t[f]=function(b){return function(){d();if(w)return null;var c=b.apply(a,arguments);c.__webglDebugContextLostId__=F;B.push(c);
return c}}(a[f])}c="getActiveAttrib getActiveUniform getBufferParameter getContextAttributes getAttachedShaders getFramebufferAttachmentParameter getParameter getProgramParameter getProgramInfoLog getRenderbufferParameter getShaderParameter getShaderInfoLog getShaderSource getTexParameter getUniform getUniformLocation getVertexAttrib".split(" ");for(b=0;b<c.length;++b)f=c[b],t[f]=function(b){return function(){d();return w?null:b.apply(a,arguments)}}(t[f]);c="isBuffer isEnabled isFramebuffer isProgram isRenderbuffer isShader isTexture".split(" ");
for(b=0;b<c.length;++b)f=c[b],t[f]=function(b){return function(){d();return w?!1:b.apply(a,arguments)}}(t[f]);t.checkFramebufferStatus=function(b){return function(){d();return w?t.FRAMEBUFFER_UNSUPPORTED:b.apply(a,arguments)}}(t.checkFramebufferStatus);t.getAttribLocation=function(b){return function(){d();return w?-1:b.apply(a,arguments)}}(t.getAttribLocation);t.getVertexAttribOffset=function(b){return function(){d();return w?0:b.apply(a,arguments)}}(t.getVertexAttribOffset);t.isContextLost=function(){return w};
return t}var s,t,x=[],A=[];t={};var F=1,w=!1,B=[],C=0,z=0,D=!1,E=0,y={};a.getContext=function(b){return function(){var c=b.apply(a,arguments);if(c instanceof WebGLRenderingContext){if(c!=s){if(s)throw"got different context";s=c;t=m(s)}return t}return c}}(a.getContext);(function(a){var c=a.addEventListener;a.addEventListener=function(d,e,f){switch(d){case "webglcontextlost":x.push(b(e));break;case "webglcontextrestored":A.push(b(e));break;default:c.apply(a,arguments)}}})(a);a.loseContext=function(){if(!w){w=
!0;C=0;for(++F;s.getError(););c();y[s.CONTEXT_LOST_WEBGL]=!0;var b=f("context lost"),d=x.slice();setTimeout(function(){for(var c=0;c<d.length;++c)d[c](b);0<=E&&setTimeout(function(){a.restoreContext()},E)},0)}};a.restoreContext=function(){w&&A.length&&setTimeout(function(){if(!D)throw"can not restore. webglcontestlost listener did not call event.preventDefault";for(var a=0;a<B.length;++a){var b=B[a];b instanceof WebGLBuffer?s.deleteBuffer(b):b instanceof WebGLFramebuffer?s.deleteFramebuffer(b):b instanceof
WebGLProgram?s.deleteProgram(b):b instanceof WebGLRenderbuffer?s.deleteRenderbuffer(b):b instanceof WebGLShader?s.deleteShader(b):b instanceof WebGLTexture&&s.deleteTexture(b)}k(s);w=!1;z=0;D=!1;for(var a=A.slice(),b=f("context restored"),c=0;c<a.length;++c)a[c](b)},0)};a.loseContextInNCalls=function(a){if(w)throw"You can not ask a lost contet to be lost";C=z+a};a.getNumCalls=function(){return z};a.setRestoreTimeout=function(a){E=a};return a},resetToInitialState:k}}();
function initWebGL(a,b,c,d,e,h){a=document.getElementById(a);return gl=WebGLUtils.setupWebGL(a)}function log(a){window.console&&window.console.log&&window.console.log(a)}
function simpleSetup(a,b,c,d,e,h){b=loadShader(a,b);c=loadShader(a,c);var k=a.createProgram();a.attachShader(k,b);a.attachShader(k,c);for(var f=0;f<d.length;++f)a.bindAttribLocation(k,f,d[f]);a.linkProgram(k);if(!a.getProgramParameter(k,a.LINK_STATUS)&&!a.isContextLost())return d=a.getProgramInfoLog(k),log("Error in program linking:"+d),a.deleteProgram(k),a.deleteProgram(c),a.deleteProgram(b),null;a.useProgram(k);a.clearColor(e[0],e[1],e[2],e[3]);a.clearDepth(h);a.enable(a.DEPTH_TEST);a.enable(a.BLEND);
a.blendFunc(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA);return k}
function loadShader(a,b){var c=document.getElementById(b);if(!c)return log("*** Error: shader script '"+b+"' not found"),null;if("x-shader/x-vertex"==c.type)var d=a.VERTEX_SHADER;else if("x-shader/x-fragment"==c.type)d=a.FRAGMENT_SHADER;else return log("*** Error: shader script '"+b+"' of undefined type '"+c.type+"'"),null;d=a.createShader(d);a.shaderSource(d,c.text);a.compileShader(d);return a.getShaderParameter(d,a.COMPILE_STATUS)||a.isContextLost()?d:(c=a.getShaderInfoLog(d),log("*** Error compiling shader '"+
b+"':"+c),a.deleteShader(d),null)}
function makeBox(a){var b=new Float32Array([1,1,1,-1,1,1,-1,-1,1,1,-1,1,1,1,1,1,-1,1,1,-1,-1,1,1,-1,1,1,1,1,1,-1,-1,1,-1,-1,1,1,-1,1,1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,1,-1,1,-1,-1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1]),c=new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,0,-1,0,0,-1,0,0,-1,0,0,-1]),d=new Float32Array([1,1,0,1,0,0,1,0,0,1,0,0,1,0,1,1,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,0,0,1,0,1,1,0,
1,0,0,1,0,1,1,0,1]),e=new Uint8Array([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23]),h={};h.normalObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h.normalObject);a.bufferData(a.ARRAY_BUFFER,c,a.STATIC_DRAW);h.texCoordObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h.texCoordObject);a.bufferData(a.ARRAY_BUFFER,d,a.STATIC_DRAW);h.vertexObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h.vertexObject);a.bufferData(a.ARRAY_BUFFER,b,a.STATIC_DRAW);
a.bindBuffer(a.ARRAY_BUFFER,null);h.indexObject=a.createBuffer();a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,h.indexObject);a.bufferData(a.ELEMENT_ARRAY_BUFFER,e,a.STATIC_DRAW);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,null);h.numIndices=e.length;return h}
function makeSphere(a,b,c,d){for(var e=[],h=[],k=[],f=[],m=0;m<=c;++m)for(var l=0;l<=d;++l){var p=m*Math.PI/c,q=2*l*Math.PI/d,n=Math.sin(p),r=Math.sin(q),p=Math.cos(p),q=Math.cos(q)*n,n=r*n,r=1-l/d,u=m/c;h.push(q);h.push(p);h.push(n);k.push(r);k.push(u);e.push(b*q);e.push(b*p);e.push(b*n)}for(m=0;m<c;++m)for(l=0;l<d;++l)b=m*(d+1)+l,q=b+d+1,f.push(b),f.push(q),f.push(b+1),f.push(q),f.push(q+1),f.push(b+1);c={};c.normalObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c.normalObject);a.bufferData(a.ARRAY_BUFFER,
new Float32Array(h),a.STATIC_DRAW);c.texCoordObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c.texCoordObject);a.bufferData(a.ARRAY_BUFFER,new Float32Array(k),a.STATIC_DRAW);c.vertexObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c.vertexObject);a.bufferData(a.ARRAY_BUFFER,new Float32Array(e),a.STATIC_DRAW);c.numIndices=f.length;c.indexObject=a.createBuffer();a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,c.indexObject);a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint16Array(f),a.STREAM_DRAW);return c}
var g_loadingObjects=[];function clearLoadingObjects(){for(var a=0;a<g_loadingObjects.length;++a)g_loadingObjects[a].onreadystatechange=void 0;g_loadingObjects=[]}function loadObj(a,b){var c={loaded:!1};c.ctx=a;var d=new XMLHttpRequest;d.obj=c;g_loadingObjects.push(d);d.onreadystatechange=function(){processLoadObj(d)};d.open("GET",b,!0);d.send(null);return c}
function processLoadObj(a){log("req="+a);4==a.readyState&&(g_loadingObjects.splice(g_loadingObjects.indexOf(a),1),doLoadObj(a.obj,a.responseText))}
function doLoadObj(a,b){vertexArray=[];normalArray=[];textureArray=[];indexArray=[];var c=[],d=[],e=[],h={},k=0,f={},m=[-1,0];f._unnamed=m;var l=b.split("\n"),p;for(p in l){var q=l[p].replace(/[ \t]+/g," ").replace(/\s\s*$/,"");if("#"!=q[0]){var n=q.split(" ");if("g"==n[0])m=[indexArray.length,0],f[n[1]]=m;else if("v"==n[0])c.push(parseFloat(n[1])),c.push(parseFloat(n[2])),c.push(parseFloat(n[3]));else if("vt"==n[0])e.push(parseFloat(n[1])),e.push(parseFloat(n[2]));else if("vn"==n[0])d.push(parseFloat(n[1])),
d.push(parseFloat(n[2])),d.push(parseFloat(n[3]));else if("f"==n[0])if(4!=n.length)log("*** Error: face '"+q+"' not handled");else for(q=1;4>q;++q){if(!(n[q]in h)){var r=n[q].split("/"),u,v;1==r.length?v=r=u=parseInt(r[0])-1:(r.length=3,u=parseInt(r[0])-1,v=parseInt(r[1])-1,r=parseInt(r[2])-1);var s=0,t=0,x=0;3*u+2<c.length&&(s=c[3*u],t=c[3*u+1],x=c[3*u+2]);vertexArray.push(s);vertexArray.push(t);vertexArray.push(x);t=s=0;2*v+1<e.length&&(s=e[2*v],t=e[2*v+1]);textureArray.push(s);textureArray.push(t);
t=s=0;x=1;3*r+2<d.length&&(s=d[3*r],t=d[3*r+1],x=d[3*r+2]);normalArray.push(s);normalArray.push(t);normalArray.push(x);h[n[q]]=k++}indexArray.push(h[n[q]]);m[1]++}}}a.normalObject=a.ctx.createBuffer();a.ctx.bindBuffer(a.ctx.ARRAY_BUFFER,a.normalObject);a.ctx.bufferData(a.ctx.ARRAY_BUFFER,new Float32Array(normalArray),a.ctx.STATIC_DRAW);a.texCoordObject=a.ctx.createBuffer();a.ctx.bindBuffer(a.ctx.ARRAY_BUFFER,a.texCoordObject);a.ctx.bufferData(a.ctx.ARRAY_BUFFER,new Float32Array(textureArray),a.ctx.STATIC_DRAW);
a.vertexObject=a.ctx.createBuffer();a.ctx.bindBuffer(a.ctx.ARRAY_BUFFER,a.vertexObject);a.ctx.bufferData(a.ctx.ARRAY_BUFFER,new Float32Array(vertexArray),a.ctx.STATIC_DRAW);a.numIndices=indexArray.length;a.indexObject=a.ctx.createBuffer();a.ctx.bindBuffer(a.ctx.ELEMENT_ARRAY_BUFFER,a.indexObject);a.ctx.bufferData(a.ctx.ELEMENT_ARRAY_BUFFER,new Uint16Array(indexArray),a.ctx.STREAM_DRAW);a.groups=f;a.loaded=!0}var g_loadingImages=[];
function clearLoadingImages(){for(var a=0;a<g_loadingImages.length;++a)g_loadingImages[a].onload=void 0;g_loadingImages=[]}function loadImageTexture(a,b){var c=a.createTexture();a.bindTexture(a.TEXTURE_2D,c);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,1,1,0,a.RGBA,a.UNSIGNED_BYTE,null);var d=new Image;g_loadingImages.push(d);d.onload=function(){doLoadImageTexture(a,d,c)};d.src=b;return c}
function doLoadImageTexture(a,b,c){g_loadingImages.splice(g_loadingImages.indexOf(b),1);a.bindTexture(a.TEXTURE_2D,c);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,b);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.bindTexture(a.TEXTURE_2D,null)}
Framerate=function(a){this.numFramerates=10;this.framerateUpdateInterval=500;this.id=a;this.renderTime=-1;this.framerates=[];myself=this;setInterval(function(){myself.updateFramerate()},this.framerateUpdateInterval)};Framerate.prototype.updateFramerate=function(){for(var a=0,b=0;b<this.framerates.length;++b)a+=this.framerates[b];a/=this.framerates.length;a=Math.round(a);document.getElementById(this.id).innerHTML="Framerate:"+a+"fps";g.framerate=a};
Framerate.prototype.snapshot=function(){if(0>this.renderTime)this.renderTime=(new Date).getTime();else{var a=(new Date).getTime(),b=a-this.renderTime;if(0!=b){for(this.framerates.push(1E3/b);this.framerates.length>this.numFramerates;)this.framerates.shift();this.renderTime=a}}};J3DIHasCSSMatrixCopy=J3DIHasCSSMatrix=!1;
J3DIMatrix4=function(a){this.$matrix=J3DIHasCSSMatrix?new WebKitCSSMatrix:{};if("object"==typeof a){if("length"in a&&16<=a.length){this.load(a);return}if(a instanceof J3DIMatrix4){this.load(a);return}}this.makeIdentity()};
J3DIMatrix4.prototype.load=function(){if(1==arguments.length&&"object"==typeof arguments[0]){var a;if(arguments[0]instanceof J3DIMatrix4){a=arguments[0].$matrix;this.$matrix.m11=a.m11;this.$matrix.m12=a.m12;this.$matrix.m13=a.m13;this.$matrix.m14=a.m14;this.$matrix.m21=a.m21;this.$matrix.m22=a.m22;this.$matrix.m23=a.m23;this.$matrix.m24=a.m24;this.$matrix.m31=a.m31;this.$matrix.m32=a.m32;this.$matrix.m33=a.m33;this.$matrix.m34=a.m34;this.$matrix.m41=a.m41;this.$matrix.m42=a.m42;this.$matrix.m43=a.m43;
this.$matrix.m44=a.m44;return}a=arguments[0];if("length"in a&&16<=a.length){this.$matrix.m11=a[0];this.$matrix.m12=a[1];this.$matrix.m13=a[2];this.$matrix.m14=a[3];this.$matrix.m21=a[4];this.$matrix.m22=a[5];this.$matrix.m23=a[6];this.$matrix.m24=a[7];this.$matrix.m31=a[8];this.$matrix.m32=a[9];this.$matrix.m33=a[10];this.$matrix.m34=a[11];this.$matrix.m41=a[12];this.$matrix.m42=a[13];this.$matrix.m43=a[14];this.$matrix.m44=a[15];return}}this.makeIdentity()};
J3DIMatrix4.prototype.getAsArray=function(){return[this.$matrix.m11,this.$matrix.m12,this.$matrix.m13,this.$matrix.m14,this.$matrix.m21,this.$matrix.m22,this.$matrix.m23,this.$matrix.m24,this.$matrix.m31,this.$matrix.m32,this.$matrix.m33,this.$matrix.m34,this.$matrix.m41,this.$matrix.m42,this.$matrix.m43,this.$matrix.m44]};J3DIMatrix4.prototype.getAsFloat32Array=function(){if(J3DIHasCSSMatrixCopy){var a=new Float32Array(16);this.$matrix.copy(a);return a}return new Float32Array(this.getAsArray())};
J3DIMatrix4.prototype.setUniform=function(a,b,c){void 0==J3DIMatrix4.setUniformArray&&(J3DIMatrix4.setUniformWebGLArray=new Float32Array(16),J3DIMatrix4.setUniformArray=Array(16));J3DIHasCSSMatrixCopy?this.$matrix.copy(J3DIMatrix4.setUniformWebGLArray):(J3DIMatrix4.setUniformArray[0]=this.$matrix.m11,J3DIMatrix4.setUniformArray[1]=this.$matrix.m12,J3DIMatrix4.setUniformArray[2]=this.$matrix.m13,J3DIMatrix4.setUniformArray[3]=this.$matrix.m14,J3DIMatrix4.setUniformArray[4]=this.$matrix.m21,J3DIMatrix4.setUniformArray[5]=
this.$matrix.m22,J3DIMatrix4.setUniformArray[6]=this.$matrix.m23,J3DIMatrix4.setUniformArray[7]=this.$matrix.m24,J3DIMatrix4.setUniformArray[8]=this.$matrix.m31,J3DIMatrix4.setUniformArray[9]=this.$matrix.m32,J3DIMatrix4.setUniformArray[10]=this.$matrix.m33,J3DIMatrix4.setUniformArray[11]=this.$matrix.m34,J3DIMatrix4.setUniformArray[12]=this.$matrix.m41,J3DIMatrix4.setUniformArray[13]=this.$matrix.m42,J3DIMatrix4.setUniformArray[14]=this.$matrix.m43,J3DIMatrix4.setUniformArray[15]=this.$matrix.m44,
J3DIMatrix4.setUniformWebGLArray.set(J3DIMatrix4.setUniformArray));a.uniformMatrix4fv(b,c,J3DIMatrix4.setUniformWebGLArray)};J3DIMatrix4.prototype.makeIdentity=function(){this.$matrix.m11=1;this.$matrix.m12=0;this.$matrix.m13=0;this.$matrix.m14=0;this.$matrix.m21=0;this.$matrix.m22=1;this.$matrix.m23=0;this.$matrix.m24=0;this.$matrix.m31=0;this.$matrix.m32=0;this.$matrix.m33=1;this.$matrix.m34=0;this.$matrix.m41=0;this.$matrix.m42=0;this.$matrix.m43=0;this.$matrix.m44=1};
J3DIMatrix4.prototype.transpose=function(){var a=this.$matrix.m12;this.$matrix.m12=this.$matrix.m21;this.$matrix.m21=a;a=this.$matrix.m13;this.$matrix.m13=this.$matrix.m31;this.$matrix.m31=a;a=this.$matrix.m14;this.$matrix.m14=this.$matrix.m41;this.$matrix.m41=a;a=this.$matrix.m23;this.$matrix.m23=this.$matrix.m32;this.$matrix.m32=a;a=this.$matrix.m24;this.$matrix.m24=this.$matrix.m42;this.$matrix.m42=a;a=this.$matrix.m34;this.$matrix.m34=this.$matrix.m43;this.$matrix.m43=a};
J3DIMatrix4.prototype.invert=function(){if(J3DIHasCSSMatrix)this.$matrix=this.$matrix.inverse();else{var a=this._determinant4x4();if(1E-8>Math.abs(a))return null;this._makeAdjoint();this.$matrix.m11/=a;this.$matrix.m12/=a;this.$matrix.m13/=a;this.$matrix.m14/=a;this.$matrix.m21/=a;this.$matrix.m22/=a;this.$matrix.m23/=a;this.$matrix.m24/=a;this.$matrix.m31/=a;this.$matrix.m32/=a;this.$matrix.m33/=a;this.$matrix.m34/=a;this.$matrix.m41/=a;this.$matrix.m42/=a;this.$matrix.m43/=a;this.$matrix.m44/=a}};
J3DIMatrix4.prototype.translate=function(a,b,c){"object"==typeof a&&"length"in a?(c=a,a=c[0],b=c[1],c=c[2]):(void 0==a&&(a=0),void 0==b&&(b=0),void 0==c&&(c=0));if(J3DIHasCSSMatrix)this.$matrix=this.$matrix.translate(a,b,c);else{var d=new J3DIMatrix4;d.$matrix.m41=a;d.$matrix.m42=b;d.$matrix.m43=c;this.multiply(d)}};
J3DIMatrix4.prototype.scale=function(a,b,c){"object"==typeof a&&"length"in a?(c=a,a=c[0],b=c[1],c=c[2]):(void 0==a&&(a=1),void 0==c?c=void 0==b?b=a:1:void 0==b&&(b=a));if(J3DIHasCSSMatrix)this.$matrix=this.$matrix.scale(a,b,c);else{var d=new J3DIMatrix4;d.$matrix.m11=a;d.$matrix.m22=b;d.$matrix.m33=c;this.multiply(d)}};
J3DIMatrix4.prototype.rotate=function(a,b,c,d){if("object"==typeof b&&"length"in b){var e=b;b=e[0];c=e[1];d=e[2]}else if(1==arguments.length)c=b=0,d=1;else if(3==arguments.length){this.rotate(a,1,0,0);this.rotate(b,0,1,0);this.rotate(c,0,0,1);return}if(J3DIHasCSSMatrix)this.$matrix=this.$matrix.rotateAxisAngle(b,c,d,a);else{a=a/180*Math.PI;a/=2;var e=Math.sin(a),h=Math.cos(a),k=e*e,f=Math.sqrt(b*b+c*c+d*d);0==f?(c=b=0,d=1):1!=f&&(b/=f,c/=f,d/=f);f=new J3DIMatrix4;if(1==b&&0==c&&0==d)f.$matrix.m11=
1,f.$matrix.m12=0,f.$matrix.m13=0,f.$matrix.m21=0,f.$matrix.m22=1-2*k,f.$matrix.m23=2*e*h,f.$matrix.m31=0,f.$matrix.m32=-2*e*h,f.$matrix.m33=1-2*k;else if(0==b&&1==c&&0==d)f.$matrix.m11=1-2*k,f.$matrix.m12=0,f.$matrix.m13=-2*e*h,f.$matrix.m21=0,f.$matrix.m22=1,f.$matrix.m23=0,f.$matrix.m31=2*e*h,f.$matrix.m32=0,f.$matrix.m33=1-2*k;else if(0==b&&0==c&&1==d)f.$matrix.m11=1-2*k,f.$matrix.m12=2*e*h,f.$matrix.m13=0,f.$matrix.m21=-2*e*h,f.$matrix.m22=1-2*k,f.$matrix.m23=0,f.$matrix.m31=0,f.$matrix.m32=
0,f.$matrix.m33=1;else{var m=b*b,l=c*c,p=d*d;f.$matrix.m11=1-2*(l+p)*k;f.$matrix.m12=2*(b*c*k+d*e*h);f.$matrix.m13=2*(b*d*k-c*e*h);f.$matrix.m21=2*(c*b*k-d*e*h);f.$matrix.m22=1-2*(p+m)*k;f.$matrix.m23=2*(c*d*k+b*e*h);f.$matrix.m31=2*(d*b*k+c*e*h);f.$matrix.m32=2*(d*c*k-b*e*h);f.$matrix.m33=1-2*(m+l)*k}f.$matrix.m14=f.$matrix.m24=f.$matrix.m34=0;f.$matrix.m41=f.$matrix.m42=f.$matrix.m43=0;f.$matrix.m44=1;this.multiply(f)}};
J3DIMatrix4.prototype.multiply=function(a){if(J3DIHasCSSMatrix)this.$matrix=this.$matrix.multiply(a.$matrix);else{var b=a.$matrix.m11*this.$matrix.m12+a.$matrix.m12*this.$matrix.m22+a.$matrix.m13*this.$matrix.m32+a.$matrix.m14*this.$matrix.m42,c=a.$matrix.m11*this.$matrix.m13+a.$matrix.m12*this.$matrix.m23+a.$matrix.m13*this.$matrix.m33+a.$matrix.m14*this.$matrix.m43,d=a.$matrix.m11*this.$matrix.m14+a.$matrix.m12*this.$matrix.m24+a.$matrix.m13*this.$matrix.m34+a.$matrix.m14*this.$matrix.m44,e=a.$matrix.m21*
this.$matrix.m11+a.$matrix.m22*this.$matrix.m21+a.$matrix.m23*this.$matrix.m31+a.$matrix.m24*this.$matrix.m41,h=a.$matrix.m21*this.$matrix.m12+a.$matrix.m22*this.$matrix.m22+a.$matrix.m23*this.$matrix.m32+a.$matrix.m24*this.$matrix.m42,k=a.$matrix.m21*this.$matrix.m13+a.$matrix.m22*this.$matrix.m23+a.$matrix.m23*this.$matrix.m33+a.$matrix.m24*this.$matrix.m43,f=a.$matrix.m21*this.$matrix.m14+a.$matrix.m22*this.$matrix.m24+a.$matrix.m23*this.$matrix.m34+a.$matrix.m24*this.$matrix.m44,m=a.$matrix.m31*
this.$matrix.m11+a.$matrix.m32*this.$matrix.m21+a.$matrix.m33*this.$matrix.m31+a.$matrix.m34*this.$matrix.m41,l=a.$matrix.m31*this.$matrix.m12+a.$matrix.m32*this.$matrix.m22+a.$matrix.m33*this.$matrix.m32+a.$matrix.m34*this.$matrix.m42,p=a.$matrix.m31*this.$matrix.m13+a.$matrix.m32*this.$matrix.m23+a.$matrix.m33*this.$matrix.m33+a.$matrix.m34*this.$matrix.m43,q=a.$matrix.m31*this.$matrix.m14+a.$matrix.m32*this.$matrix.m24+a.$matrix.m33*this.$matrix.m34+a.$matrix.m34*this.$matrix.m44,n=a.$matrix.m41*
this.$matrix.m11+a.$matrix.m42*this.$matrix.m21+a.$matrix.m43*this.$matrix.m31+a.$matrix.m44*this.$matrix.m41,r=a.$matrix.m41*this.$matrix.m12+a.$matrix.m42*this.$matrix.m22+a.$matrix.m43*this.$matrix.m32+a.$matrix.m44*this.$matrix.m42,u=a.$matrix.m41*this.$matrix.m13+a.$matrix.m42*this.$matrix.m23+a.$matrix.m43*this.$matrix.m33+a.$matrix.m44*this.$matrix.m43,v=a.$matrix.m41*this.$matrix.m14+a.$matrix.m42*this.$matrix.m24+a.$matrix.m43*this.$matrix.m34+a.$matrix.m44*this.$matrix.m44;this.$matrix.m11=
a.$matrix.m11*this.$matrix.m11+a.$matrix.m12*this.$matrix.m21+a.$matrix.m13*this.$matrix.m31+a.$matrix.m14*this.$matrix.m41;this.$matrix.m12=b;this.$matrix.m13=c;this.$matrix.m14=d;this.$matrix.m21=e;this.$matrix.m22=h;this.$matrix.m23=k;this.$matrix.m24=f;this.$matrix.m31=m;this.$matrix.m32=l;this.$matrix.m33=p;this.$matrix.m34=q;this.$matrix.m41=n;this.$matrix.m42=r;this.$matrix.m43=u;this.$matrix.m44=v}};
J3DIMatrix4.prototype.divide=function(a){this.$matrix.m11/=a;this.$matrix.m12/=a;this.$matrix.m13/=a;this.$matrix.m14/=a;this.$matrix.m21/=a;this.$matrix.m22/=a;this.$matrix.m23/=a;this.$matrix.m24/=a;this.$matrix.m31/=a;this.$matrix.m32/=a;this.$matrix.m33/=a;this.$matrix.m34/=a;this.$matrix.m41/=a;this.$matrix.m42/=a;this.$matrix.m43/=a;this.$matrix.m44/=a};
J3DIMatrix4.prototype.ortho=function(a,b,c,d,e,h){var k=(a+b)/(a-b),f=(d+c)/(d-c),m=(h+e)/(h-e),l=new J3DIMatrix4;l.$matrix.m11=2/(a-b);l.$matrix.m12=0;l.$matrix.m13=0;l.$matrix.m14=0;l.$matrix.m21=0;l.$matrix.m22=2/(d-c);l.$matrix.m23=0;l.$matrix.m24=0;l.$matrix.m31=0;l.$matrix.m32=0;l.$matrix.m33=-2/(h-e);l.$matrix.m34=0;l.$matrix.m41=k;l.$matrix.m42=f;l.$matrix.m43=m;l.$matrix.m44=1;this.multiply(l)};
J3DIMatrix4.prototype.frustum=function(a,b,c,d,e,h){var k=new J3DIMatrix4;k.$matrix.m11=2*e/(b-a);k.$matrix.m12=0;k.$matrix.m13=0;k.$matrix.m14=0;k.$matrix.m21=0;k.$matrix.m22=2*e/(d-c);k.$matrix.m23=0;k.$matrix.m24=0;k.$matrix.m31=(b+a)/(b-a);k.$matrix.m32=(d+c)/(d-c);k.$matrix.m33=-(h+e)/(h-e);k.$matrix.m34=-1;k.$matrix.m41=0;k.$matrix.m42=0;k.$matrix.m43=-(2*h*e)/(h-e);k.$matrix.m44=0;this.multiply(k)};
J3DIMatrix4.prototype.perspective=function(a,b,c,d){a=Math.tan(a*Math.PI/360)*c;var e=-a;this.frustum(b*e,b*a,e,a,c,d)};
J3DIMatrix4.prototype.lookat=function(a,b,c,d,e,h,k,f,m){"object"==typeof c&&"length"in c&&(k=c[0],f=c[1],m=c[2],c=b,d=c[0],e=c[1],h=c[2],c=a,a=c[0],b=c[1],c=c[2]);var l=new J3DIMatrix4;d=a-d;e=b-e;h=c-h;var p=Math.sqrt(d*d+e*e+h*h);p&&(d/=p,e/=p,h/=p);xx=f*h-m*e;xy=-k*h+m*d;xz=k*e-f*d;f=-d*xz+h*xx;k=d*xy-e*xx;if(p=Math.sqrt(xx*xx+xy*xy+xz*xz))xx/=p,xy/=p,xz/=p;if(p=Math.sqrt(k*k+f*f+m*m))k/=p,f/=p,m/=p;l.$matrix.m11=xx;l.$matrix.m12=xy;l.$matrix.m13=xz;l.$matrix.m14=0;l.$matrix.m21=k;l.$matrix.m22=
f;l.$matrix.m23=m;l.$matrix.m24=0;l.$matrix.m31=d;l.$matrix.m32=e;l.$matrix.m33=h;l.$matrix.m34=0;l.$matrix.m41=0;l.$matrix.m42=0;l.$matrix.m43=0;l.$matrix.m44=1;l.translate(-a,-b,-c);this.multiply(l)};
J3DIMatrix4.prototype.decompose=function(a,b,c,d,e){if(0==this.$matrix.m44)return!1;var h;a=void 0!=a&&"length"in a?a:new J3DIVector3;b=void 0!=b&&"length"in b?b:new J3DIVector3;c=void 0!=c&&"length"in c?c:new J3DIVector3;d=void 0!=d&&"length"in d?d:new J3DIVector3;h=void 0!=e&&"length"in e?e:Array(4);e=new J3DIMatrix4(this);e.divide(e.$matrix.m44);var k=new J3DIMatrix4(e);k.$matrix.m14=0;k.$matrix.m24=0;k.$matrix.m34=0;k.$matrix.m44=1;if(0==k._determinant4x4())return!1;if(0!=e.$matrix.m14||0!=e.$matrix.m24||
0!=e.$matrix.m34){var f=[e.$matrix.m14,e.$matrix.m24,e.$matrix.m34,e.$matrix.m44],k=new J3DIMatrix4(k);k.invert();k=new J3DIMatrix4(k);k.transpose();k.multVecMatrix(h,f);e.$matrix.m14=e.$matrix.m24=e.$matrix.m34=0;e.$matrix.m44=1}else h[0]=h[1]=h[2]=0,h[3]=1;a[0]=e.$matrix.m41;e.$matrix.m41=0;a[1]=e.$matrix.m42;e.$matrix.m42=0;a[2]=e.$matrix.m43;e.$matrix.m43=0;a=new J3DIVector3(e.$matrix.m11,e.$matrix.m12,e.$matrix.m13);h=new J3DIVector3(e.$matrix.m21,e.$matrix.m22,e.$matrix.m23);e=new J3DIVector3(e.$matrix.m31,
e.$matrix.m32,e.$matrix.m33);c[0]=a.vectorLength();a.divide(c[0]);d[0]=a.dot(h);h.combine(a,1,-d[0]);c[1]=h.vectorLength();h.divide(c[1]);d[0]/=c[1];d[1]=h.dot(e);e.combine(a,1,-d[1]);d[2]=h.dot(e);e.combine(h,1,-d[2]);c[2]=e.vectorLength();e.divide(c[2]);d[1]/=c[2];d[2]/=c[2];d=new J3DIVector3(h);d.cross(e);if(0>a.dot(d))for(i=0;3>i;i++)c[i]*=-1,row[0][i]*=-1,row[1][i]*=-1,row[2][i]*=-1;b[1]=Math.asin(e[0]);0!=Math.cos(b[1])?(b[0]=Math.atan2(-e[1],e[2]),b[2]=Math.atan2(-h[0],a[0])):(b[2]=0,c=Math.sin(b[1]),
b[0]=0>c?Math.acos((a[2]+h[1])/(1-c))+b[2]:Math.asin((h[2]+a[1])/(c+1))-b[2]);c=180/Math.PI;b[0]*=c;b[1]*=c;b[2]*=c;return!0};J3DIMatrix4.prototype._determinant2x2=function(a,b,c,d){return a*d-b*c};J3DIMatrix4.prototype._determinant3x3=function(a,b,c,d,e,h,k,f,m){return a*this._determinant2x2(e,h,f,m)-d*this._determinant2x2(b,c,f,m)+k*this._determinant2x2(b,c,e,h)};
J3DIMatrix4.prototype._determinant4x4=function(){var a=this.$matrix.m12,b=this.$matrix.m13,c=this.$matrix.m14,d=this.$matrix.m21,e=this.$matrix.m22,h=this.$matrix.m23,k=this.$matrix.m24,f=this.$matrix.m31,m=this.$matrix.m32,l=this.$matrix.m33,p=this.$matrix.m34,q=this.$matrix.m41,n=this.$matrix.m42,r=this.$matrix.m43,u=this.$matrix.m44;return this.$matrix.m11*this._determinant3x3(e,m,n,h,l,r,k,p,u)-a*this._determinant3x3(d,f,q,h,l,r,k,p,u)+b*this._determinant3x3(d,f,q,e,m,n,k,p,u)-c*this._determinant3x3(d,
f,q,e,m,n,h,l,r)};
J3DIMatrix4.prototype._makeAdjoint=function(){var a=this.$matrix.m11,b=this.$matrix.m12,c=this.$matrix.m13,d=this.$matrix.m14,e=this.$matrix.m21,h=this.$matrix.m22,k=this.$matrix.m23,f=this.$matrix.m24,m=this.$matrix.m31,l=this.$matrix.m32,p=this.$matrix.m33,q=this.$matrix.m34,n=this.$matrix.m41,r=this.$matrix.m42,u=this.$matrix.m43,v=this.$matrix.m44;this.$matrix.m11=this._determinant3x3(h,l,r,k,p,u,f,q,v);this.$matrix.m21=-this._determinant3x3(e,m,n,k,p,u,f,q,v);this.$matrix.m31=this._determinant3x3(e,
m,n,h,l,r,f,q,v);this.$matrix.m41=-this._determinant3x3(e,m,n,h,l,r,k,p,u);this.$matrix.m12=-this._determinant3x3(b,l,r,c,p,u,d,q,v);this.$matrix.m22=this._determinant3x3(a,m,n,c,p,u,d,q,v);this.$matrix.m32=-this._determinant3x3(a,m,n,b,l,r,d,q,v);this.$matrix.m42=this._determinant3x3(a,m,n,b,l,r,c,p,u);this.$matrix.m13=this._determinant3x3(b,h,r,c,k,u,d,f,v);this.$matrix.m23=-this._determinant3x3(a,e,n,c,k,u,d,f,v);this.$matrix.m33=this._determinant3x3(a,e,n,b,h,r,d,f,v);this.$matrix.m43=-this._determinant3x3(a,
e,n,b,h,r,c,k,u);this.$matrix.m14=-this._determinant3x3(b,h,l,c,k,p,d,f,q);this.$matrix.m24=this._determinant3x3(a,e,m,c,k,p,d,f,q);this.$matrix.m34=-this._determinant3x3(a,e,m,b,h,l,d,f,q);this.$matrix.m44=this._determinant3x3(a,e,m,b,h,l,c,k,p)};J3DIVector3=function(a,b,c){this.load(a,b,c)};J3DIVector3.prototype.load=function(a,b,c){"object"==typeof a&&"length"in a?(this[0]=a[0],this[1]=a[1],this[2]=a[2]):"number"==typeof a?(this[0]=a,this[1]=b,this[2]=c):(this[0]=0,this[1]=0,this[2]=0)};
J3DIVector3.prototype.getAsArray=function(){return[this[0],this[1],this[2]]};J3DIVector3.prototype.getAsFloat32Array=function(){return new Float32Array(this.getAsArray())};J3DIVector3.prototype.vectorLength=function(){return Math.sqrt(this[0]*this[0]+this[1]*this[1]+this[2]*this[2])};J3DIVector3.prototype.divide=function(a){this[0]/=a;this[1]/=a;this[2]/=a};
J3DIVector3.prototype.cross=function(a){var b=this[1]*a[2]-this[2]*a[1],c=-this[0]*a[2]+this[2]*a[0];this[2]=this[0]*a[1]-this[1]*a[0];this[0]=b;this[1]=c};J3DIVector3.prototype.dot=function(a){return this[0]*a[0]+this[1]*a[1]+this[2]*a[2]};J3DIVector3.prototype.combine=function(a,b,c){this[0]=b*this[0]+c*a[0];this[1]=b*this[1]+c*a[1];this[2]=b*this[2]+c*a[2]};
J3DIVector3.prototype.multVecMatrix=function(a){var b=this[0],c=this[1],d=this[2];this[0]=a.$matrix.m41+b*a.$matrix.m11+c*a.$matrix.m21+d*a.$matrix.m31;this[1]=a.$matrix.m42+b*a.$matrix.m12+c*a.$matrix.m22+d*a.$matrix.m32;this[2]=a.$matrix.m43+b*a.$matrix.m13+c*a.$matrix.m23+d*a.$matrix.m33;a=a.$matrix.m44+b*a.$matrix.m14+c*a.$matrix.m24+d*a.$matrix.m34;1!=a&&0!=a&&(this[0]/=a,this[1]/=a,this[2]/=a)};J3DIVector3.prototype.toString=function(){return"["+this[0]+","+this[1]+","+this[2]+"]"};var g={};
function makeGround(a){var b=new Float32Array([100,0,100,100,0,-100,-100,0,-100,-100,0,100]),c=new Float32Array([0,1,0,0,1,0,0,1,0,0,1,0]),d=new Float32Array([1,0,1,1,0,1,0,0]),e=new Uint8Array([0,1,2,0,2,3]),h={};h.normalObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h.normalObject);a.bufferData(a.ARRAY_BUFFER,c,a.STATIC_DRAW);h.texCoordObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h.texCoordObject);a.bufferData(a.ARRAY_BUFFER,d,a.STATIC_DRAW);h.vertexObject=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,
h.vertexObject);a.bufferData(a.ARRAY_BUFFER,b,a.STATIC_DRAW);a.bindBuffer(a.ARRAY_BUFFER,null);h.indexObject=a.createBuffer();a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,h.indexObject);a.bufferData(a.ELEMENT_ARRAY_BUFFER,e,a.STATIC_DRAW);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,null);h.numIndices=e.length;return h}
function init(){var a=initWebGL("canvas");if(a)return g.vprogram=simpleSetup(a,"vshader","fshader",["vNormal","vTexCoord","vPosition"],[.6,.6,.8,1],1E4),g.fprogram=simpleSetup(a,"ground-vshader","ground-fshader",["aVertexPosition","aVertexNormal","aTextureCoord"],[.5,.5,.5,1],1E4),g.program=g.vprogram,a.useProgram(g.program),a.uniform3f(a.getUniformLocation(g.program,"lightDir"),.7,.7,.5),a.uniform1i(a.getUniformLocation(g.program,"sampler2d"),0),g.box=makeBox(a),g.ground=makeGround(a),g.crateTexture=
loadImageTexture(a,"crate.jpg"),g.crate2Texture=loadImageTexture(a,"crate2.jpg"),g.crate3Texture=loadImageTexture(a,"crate3.png"),g.grassTexture=loadImageTexture(a,"grass.jpg"),g.bgTexture=loadImageTexture(a,"bg2.jpg"),g.u_normalMatrixLoc=a.getUniformLocation(g.program,"u_normalMatrix"),g.u_modelViewProjMatrixLoc=a.getUniformLocation(g.program,"u_modelViewProjMatrix"),a}
function audioInit(){try{return window.AudioContext=window.AudioContext||window.webkitAudioContext,new AudioContext}catch(a){return console.log("could not initialize web audio: "+a),null}}var requestId;
function reshape(a){if(g.canvas.clientWidth!=g.canvas.width||g.canvas.clientHeight!=g.canvas.height)g.canvas.width=g.canvas.clientWidth,g.canvas.height=g.canvas.clientHeight,a.viewport(0,0,g.canvas.clientWidth,g.canvas.clientHeight),g.perspectiveMatrix=new J3DIMatrix4,g.perspectiveMatrix.perspective(40,g.canvas.clientWidth/g.canvas.clientHeight,1,1E4),g.perspectiveMatrix.lookat(0,0,20,0,0,0,0,1,0)}
function drawBox(a,b,c,d,e,h,k,f){var m=new J3DIMatrix4;m.rotate(b,0,0,1);m.translate(d,e-1.5,h);m.rotate(c,0,1,0);m.scale(k,k,k);b=new J3DIMatrix4(m);b.invert();b.transpose();b.setUniform(a,g.u_normalMatrixLoc,!1);b=new J3DIMatrix4(g.perspectiveMatrix);b.multiply(m);b.setUniform(a,g.u_modelViewProjMatrixLoc,!1);a.bindTexture(a.TEXTURE_2D,f);a.drawElements(a.TRIANGLES,g.box.numIndices,a.UNSIGNED_BYTE,0)}
function drawGround(a,b,c,d,e,h,k,f){var m=new J3DIMatrix4;m.rotate(b,0,0,1);m.translate(d,e-2.5,h);m.rotate(c,1,0,0);m.scale(k,k,k);b=new J3DIMatrix4(m);b.invert();b.transpose();b.setUniform(a,g.u_normalMatrixLoc,!1);b=new J3DIMatrix4(g.perspectiveMatrix);b.multiply(m);b.setUniform(a,g.u_modelViewProjMatrixLoc,!1);a.bindTexture(a.TEXTURE_2D,f);a.drawElements(a.TRIANGLES,g.ground.numIndices,a.UNSIGNED_BYTE,0)}
function loadSound(a,b){var c=new XMLHttpRequest;c.open("GET",b,!0);c.responseType="arraybuffer";c.onload=function(){a.decodeAudioData(c.response,function(b){g.gainNode=a.createGain();playSound(a,b,0);console.log(b.duration);setInterval(function(){playSound(a,b,0)},1E3*b.duration)},function(){console.log("error loading audio")})};c.send()}function playSound(a,b,c){var d=a.createBufferSource();d.buffer=b;d.connect(g.gainNode);g.gainNode.connect(a.destination);d.start(c)}
function toggleSound(){console.log(g.gainNode.gain.value);0!=g.gainNode.gain.value?(g.gainNode.gain.value=0,document.getElementById("button1").style.display="none",document.getElementById("button2").style.display="block"):(g.gainNode.gain.value=1,document.getElementById("button1").style.display="block",document.getElementById("button2").style.display="none");console.log(g.gainNode.gain.value)}
function drawPicture(a){reshape(a);a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT);a.enableVertexAttribArray(0);a.enableVertexAttribArray(1);a.enableVertexAttribArray(2);a.bindBuffer(a.ARRAY_BUFFER,g.ground.vertexObject);a.vertexAttribPointer(2,3,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,g.ground.normalObject);a.vertexAttribPointer(0,3,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,g.ground.texCoordObject);a.vertexAttribPointer(1,2,a.FLOAT,!1,0,0);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,g.ground.indexObject);
drawGround(a,g.cam.angle,90,0,150,-250,2,g.bgTexture);drawGround(a,g.cam.angle,0,g.groundx,0,g.groundz,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx,0,g.groundz-200,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx,0,g.groundz-400,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx+200,0,g.groundz,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx+200,0,g.groundz-200,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx+200,0,g.groundz-400,1,g.grassTexture);drawGround(a,g.cam.angle,
0,g.groundx-200,0,g.groundz,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx-200,0,g.groundz-200,1,g.grassTexture);drawGround(a,g.cam.angle,0,g.groundx-200,0,g.groundz-400,1,g.grassTexture);a.enableVertexAttribArray(0);a.enableVertexAttribArray(1);a.enableVertexAttribArray(2);a.bindBuffer(a.ARRAY_BUFFER,g.box.vertexObject);a.vertexAttribPointer(2,3,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,g.box.normalObject);a.vertexAttribPointer(0,3,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,g.box.texCoordObject);
a.vertexAttribPointer(1,2,a.FLOAT,!1,0,0);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,g.box.indexObject);for(var b=0;80>b;b++)1==g.allboxpos[b].tex?drawBox(a,g.cam.angle,g.allboxpos[b].angle,g.allboxpos[b].x,g.allboxpos[b].y,g.allboxpos[b].z,1,g.crateTexture):2==g.allboxpos[b].tex?drawBox(a,g.cam.angle,g.allboxpos[b].angle,g.allboxpos[b].x,g.allboxpos[b].y,g.allboxpos[b].z,1,g.crate2Texture):3==g.allboxpos[b].tex?drawBox(a,g.cam.angle,g.allboxpos[b].angle,g.allboxpos[b].x,g.allboxpos[b].y,g.allboxpos[b].z,
1,g.crate3Texture):0==g.allboxpos[b].tex&&drawBox(a,g.cam.angle,g.allboxpos[b].angle,g.allboxpos[b].x,g.allboxpos[b].y,g.allboxpos[b].z,1,null);a.bindTexture(a.TEXTURE_2D,null);g.ups||framerate.snapshot()}
function update(){g.leftKeyDown?(g.cam.xv=.2*g.cam.zv,-10<g.cam.angle&&0!=g.cam.zv&&g.cam.angle--):0>g.cam.angle&&g.cam.angle++;g.rightKeyDown?(g.cam.xv=-.2*g.cam.zv,10>g.cam.angle&&0!=g.cam.zv&&g.cam.angle++):0<g.cam.angle&&g.cam.angle--;g.upKeyDown&&(g.cam.zv-=.04);g.leftKeyDown&&g.rightKeyDown&&(0>g.cam.angle&&g.cam.angle++,0<g.cam.angle&&g.cam.angle--,g.cam.xv=0);40<g.distance&&!g.hitFourty&&(g.hitFourty=!0,document.getElementById("menu").style.display="none",document.getElementById("save").style.display=
"none",document.getElementById("highscores").style.display="none");for(var a=0;80>a;a++){23<g.allboxpos[a].z&&(2E3<g.distance&&(g.allboxpos[a].tex=2,5E3<g.distance&&(g.allboxpos[a].tex=3,1E4<g.distance&&(g.allboxpos[a].tex=0))),g.allboxpos[a].x=200*Math.random()-100,g.allboxpos[a].z=-200*Math.random()-150,g.allboxpos[a].angle=90*Math.random(),g.distance++);if(1.7>g.allboxpos[a].x&&-1.7<g.allboxpos[a].x&&15<g.allboxpos[a].z){var b=g.avgVelocity,c=g.distance;console.log("vel = "+-g.cam.zv);console.log("dis = "+
g.distance);console.log("avgV= "+g.avgVelocity);g.ups=!0;setTimeout(function(){console.log("fps = "+g.framerate);55<g.framerate?g.score=Math.round(.05*c*b*b):(g.score=Math.round(.1*c*b/(60/g.framerate)),g.score=0);document.getElementById("menu").innerHTML="Game Over<br>Score = "+g.score;console.log("score= "+g.score);document.getElementById("menu").style.display="block";getScores();document.getElementById("highscores").style.display="block";document.getElementById("save").style.display="block"},500);
g.avgVelocity=0;g.distance=0;g.ticks=0;g.cam.zv=0;g.allboxpos[a].z=24;for(var d=0;80>d;d++)g.allboxpos[d].tex=1;g.hitFourty=!1;g.leftKeyDown=!1;g.rightKeyDown=!1;g.upKeyDown=!1;g.cam.angle=0;g.cam.xv=0}g.allboxpos[a].x-=g.cam.xv;g.allboxpos[a].z-=g.cam.zv}g.avgVelocity=(g.avgVelocity*g.ticks-g.cam.zv)/(g.ticks+1);0!=g.cam.zv&&g.ticks++;g.groundx-=g.cam.xv;g.groundz-=g.cam.zv;200<g.groundz&&(g.groundz=0);if(200<g.groundx||-200>g.groundx)g.groundx=0;document.getElementById("score").innerHTML="Velocity = "+
Math.round(10*-g.cam.zv);document.getElementById("distance").innerHTML="Distance = "+Math.round(g.distance);g.ups&&framerate.snapshot()}function removeDialog(){document.getElementById("save").style.display="none"}
function onKeyPress(a){var b=a.keyCode;switch(b){case 27:a.preventDefault();g.hitFourty=!0;document.getElementById("menu").style.display="none";document.getElementById("save").style.display="none";document.getElementById("highscores").style.display="none";break;case 37:a.preventDefault();g.leftKeyDown=!0;break;case 38:a.preventDefault();g.upKeyDown=!0;break;case 39:a.preventDefault();g.rightKeyDown=!0;break;case 70:g.ups=!1;break;case 72:"none"==document.getElementById("save").style.display&&(getScores(),
document.getElementById("highscores").style.display="block");break;case 85:g.ups=!0;break;default:console.log(b)}}function onKeyUp(a){a.preventDefault();a=a.keyCode;switch(a){case 37:g.leftKeyDown=!1;g.cam.xv=0;break;case 38:g.upKeyDown=!1;break;case 39:g.rightKeyDown=!1;g.cam.xv=0;break;case 72:g.hitFourty&&(document.getElementById("highscores").style.display="none");break;default:console.log(a)}}
function main(){g.canvas=document.getElementById("canvas");document.getElementById("button2").style.display="none";g.cam={xv:0,zv:0,angle:0};g.groundz=0;g.groundx=0;g.leftKeyDown=!1;g.rightKeyDown=!1;g.upKeyDown=!1;g.distance=0;g.avgVelocity=0;g.ticks=0;g.score=0;g.hitFourty=!1;g.framerate=0;g.ups=!1;g.audioBuffer=null;g.gainNode=null;g.allboxpos=[];for(var a=0;80>a;a++)g.allboxpos.push({x:0,y:0,z:0,angle:0,tex:1}),g.allboxpos[a].x=200*Math.random()-100,g.allboxpos[a].z=-200*Math.random(),g.allboxpos[a].angle=
90*Math.random();g.canvas.addEventListener("webglcontextlost",function(a){a.preventDefault();clearLoadingImages();void 0!==requestId&&(window.cancelAnimFrame(requestId),requestId=void 0)},!1);g.canvas.addEventListener("webglcontextrestored",function(){init();c()},!1);document.addEventListener("keydown",onKeyPress,!1);document.addEventListener("keyup",onKeyUp,!1);var a=audioInit(),b=init();if(b){loadSound(a,"sc.mp3");setInterval(update,1E3/60);framerate=new Framerate("framerate");var c=function(){drawPicture(b);
requestId=window.requestAnimFrame(c,g.canvas)};c()}}window.main=main;window.saveScore=saveScore;window.removeDialog=removeDialog;window.toggleSound=toggleSound;
